# https://developers.redhat.com/blog/2017/10/04/configuring-spring-boot-kubernetes-secrets#setup
# kubectl create secret generic djmz-secret \
#  --from-literal=spring.data.mongodb.uri=mongodb://localhost:27018/product-service \
#  --from-literal=spring.user.name=vms \
#  --from-literal=spring.user.password=xxx \

#  --from-literal=auth.db.driver=com.mysql.cj.jdbc.Driver \
#  --from-literal=auth.db.uri=jdbc:mysql://localhost:3306/inventoryservice \
#  --from-literal=auth.db.user=root \
#  --from-literal=auth.db.passwd=mysql \
#  --from-literal=auth.db.ddl-auto=update \

apiVersion: v1
kind: Secret
metadata:
  name: djmz-secret
  namespace: djmz
data:
  my12_username: dm1z
  my12_password: ZW5jaG94
  my12_database: cG9zdGdyZXM=
  my12_host: NTAuMjIuMTAzLjEzMQ==
  my12_port: NTQzMg==

---

spec:
  template:
    spec:
      containers:
        - env:
            - name: SECRETS_MY12_USER
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: spring.user.name
            - name: SECRETS_MY12_PASSWD
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: spring.user.password
            - name: SECRET_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: spring.data.mongodb.uri

            - name: SECRET_AUTH_DB_DRIVER
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: auth.db.driver
            - name: SECRET_AUTH_DB_URI
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: auth.db.uri
            - name: SECRET_AUTH_DB_USER
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: auth.db.user
            - name: SECRET_AUTH_DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: auth.db.passwd
            - name: SECRET_AUTH_DB_DDL
              valueFrom:
                secretKeyRef:
                  name: djmz-secret
                  key: auth.db.ddl-auto
