# Secret: SECRET_MONGO_URI: djmz-secret/spring.data.mongodb.uri
# spring.data.mongodb/uri=mongodb://localhost:27018/product-service
security.user.name=${SECRET_MONGO_URI:mongodb://localhost:27018/media-service}

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.application.name=product-service

# Hardcoded port
server.port=8084
# Discovery server
# server.port=0


#Keycloak.  https://www.baeldung.com/spring-boot-keycloak
#https://stackoverflow.com/questions/58096293/keycloak-with-spring-boot-code-to-token-error
#keycloak.auth-server-url=http://localhost:8180/
#keycloak.realm=Services
#keycloak.resource=product-app
#keycloak.credentials.secret=5c1H4o1jZ9Q0iPST0CBsBQ1mhJVwaRPK
#
#keycloak.security-constraints[0].authRoles[0]=user
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/api/product/*
#
#keycloak.principal-attribute=preferred_username
#
##keycloak.public-client=true
##keycloak.ssl-required=external
