spring.data.mongodb.uri= mongodb+srv://acmclarenfrank:Hopping58@cluster0.ciryljx.mongodb.net/Products?retryWrites=true&w=majority
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka
spring.application.name=product-service
server.port=8080