#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://${AUTH_DB_HOST}/${AUTH_DB_NAME}?useSSL=false
spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.show_sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
