apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "media-service.fullname" . }}
  labels:
    {{- include "media-service.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
