{{- if include "media-service.createMongoUriSecret" . }}
{{- $uri := .Values.externalMongodb.uri }}
{{- if .Values.mongodb.enabled }}
{{- $host := printf "%s:27017" (include "media-service.mongodb.fullname" .) }}
{{- if .Values.mongodb.auth.enabled }}
{{- $uri = printf "mongodb://%s:%s@%s/%s?authSource=admin" (.Values.mongodb.auth.rootUser | urlquery) (.Values.mongodb.auth.rootPassword | urlquery) $host .Values.mongodb.database }}
{{- else }}
{{- $uri = printf "mongodb://%s/%s" $host .Values.mongodb.database }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "media-service.mongoUriSecretName" . }}
  labels:
    {{- include "media-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: {{ $uri | quote }}
{{- end }}
