apiVersion: v1
kind: StatefulSet
metadata:
  name: elk-cluster
  namespace: elk-local-pv
spec:
  replicas: 3
  volumeClaimTemplates:
  - kind: PersistentVolumeClaim
    metadata:
      name: elk-data
    spec:
      resource:
        requests:
          storage: 100Gi
      storageClassName: ssd-disks




