apiVersion: apps/v1
kind: StatefulSet  # Kind of Kubernetes resource we are creating.
metadata:
  name: keycloak

spec:
  selector:
    matchLabels:
      app: keycloak
  serviceName: keycloak-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
        networking/allow-internet-egress: "true"
    spec:
      containers:
        - name: keycloak
          image: cafrank/kclatest     # My docker container image
          #image: localhost:32000/kclatest     # My docker container image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443   # the port that the container is running on in the cluster
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: 34.82.33.112
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: spock
            - name: AUTH_DB_URL
              value: jdbc:postgresql:34.82.33.112
            - name: AUTH_DB_HOST
              value: 34.82.33.112
            - name: AUTH_DB_NAME
              value: postgres
            - name: AUTH_DB_USER
              value: postgres
            - name: AUTH_DB_PASSWORD
              value: spock

---
apiVersion: v1
kind: Service  # Kind of Kubernetes resource we are creating.  Load balancer
metadata:
  name: keycloak-svc

spec:
  selector:
    app: keycloak
  ports:
    - protocol: "TCP"
      port: 8443    # Port the service is running on in the cluster.
      targetPort: 8443  # Port exposed by the service
#  type: NodePort

